### ISSUE TITLE
Top README examples do not work

### ISSUE THREAD

**Issue by antononcube** [avuserow/raku-sql-builder#1]
This usage example does not work:

```perl6
# many SQL fragments are supported:
my $q2 = $sql.from('songs').
    select('album', (:albumlength(Fn.new('SUM', 'length'))).
    where([:online(True), ['year', '>=', 2020]).
    group-by('album').
    order-by('album');
```

I get the error:

> Unable to parse expression in array composer; couldn't find final ']' (corresponding starter was at line 17)

After adding the missing ']' I get the error:

> No such method 'where' for invocant of type 'Pair'.  Did you mean 'WHERE'?

**Comment by avuserow** [comment]
Thanks for trying it out. The typo was not obvious. I've fixed the docs, and added a test case for this.

I'll also see if I can get something set up to automatically test the examples in the docs. That seems a good fit for this.
